# Generated by Django 4.0.5 on 2022-06-05 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_user_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
